# Generated by Django 3.2.9 on 2022-02-26 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20220226_0836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='bank_cart',
            new_name='bank_card',
        ),
    ]
