# Generated by Django 3.2.9 on 2022-03-01 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_rename_bank_cart_order_bank_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
        migrations.AddField(
            model_name='order',
            name='fio',
            field=models.CharField(default=1, max_length=150, verbose_name='ФИО'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Оплачено'),
        ),
    ]
