# Generated by Django 3.2.9 on 2022-02-21 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20220221_1208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratingstar',
            options={'ordering': ['-value'], 'verbose_name': 'Звезда к рейтингу', 'verbose_name_plural': 'Звезды к рейтингу'},
        ),
    ]
