# Generated by Django 3.2.9 on 2022-02-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20220220_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='composition',
            field=models.TextField(null=True, verbose_name='Состав'),
        ),
        migrations.AddField(
            model_name='products',
            name='mode_of_application',
            field=models.TextField(null=True, verbose_name='Способ применения'),
        ),
        migrations.AddField(
            model_name='products',
            name='pharmacological_effect',
            field=models.TextField(null=True, verbose_name='Фармакологический эффект'),
        ),
        migrations.AddField(
            model_name='products',
            name='product_features',
            field=models.TextField(null=True, verbose_name='Особенности продукта'),
        ),
    ]
