# Generated by Django 3.2.9 on 2022-02-22 12:53

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_ratingstar_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='star',
            field=models.ForeignKey(default=1, on_delete=django.db.models.fields.CharField, to='shop.rating', verbose_name='Звезды'),
            preserve_default=False,
        ),
    ]
