# Generated by Django 3.2.9 on 2022-02-20 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20220220_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='composition',
            field=models.TextField(blank=True, null=True, verbose_name='Состав'),
        ),
        migrations.AlterField(
            model_name='products',
            name='mode_of_application',
            field=models.TextField(blank=True, null=True, verbose_name='Способ применения'),
        ),
        migrations.AlterField(
            model_name='products',
            name='pharmacological_effect',
            field=models.TextField(blank=True, null=True, verbose_name='Фармакологический эффект'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_features',
            field=models.TextField(blank=True, null=True, verbose_name='Особенности продукта'),
        ),
    ]
