# Generated by Django 3.2.9 on 2022-02-24 13:57

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_reviews_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='star',
            field=models.ForeignKey(on_delete=django.db.models.fields.CharField, to='shop.ratingstar', verbose_name='Звезды'),
        ),
    ]
