# Generated by Django 3.2.9 on 2022-02-20 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20220220_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='composition',
        ),
        migrations.RemoveField(
            model_name='products',
            name='mode_of_application',
        ),
        migrations.RemoveField(
            model_name='products',
            name='pharmacological_effect',
        ),
        migrations.RemoveField(
            model_name='products',
            name='product_features',
        ),
    ]
