# Generated by Django 3.2.9 on 2022-02-14 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20220214_1719'),
        ('shop', '0006_auto_20220214_1654'),
    ]

    operations = [
    ]
