# Generated by Django 3.2.9 on 2022-02-21 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_reviews_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='composition',
        ),
        migrations.RemoveField(
            model_name='products',
            name='mode_of_application',
        ),
        migrations.RemoveField(
            model_name='products',
            name='pharmacological_effect',
        ),
        migrations.RemoveField(
            model_name='products',
            name='product_features',
        ),
    ]
