# Generated by Django 3.2.9 on 2022-02-14 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_rename_name_subcategories_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='subcategory',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='shop.subcategories', verbose_name='СубКатегория'),
            preserve_default=False,
        ),
    ]
