# Generated by Django 3.2.9 on 2022-02-21 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_products_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['-discount'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.RemoveField(
            model_name='products',
            name='favorites',
        ),
    ]
