# Generated by Django 3.2.9 on 2022-02-26 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20220221_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='detail',
            field=models.TextField(default='default title', verbose_name='Детали'),
            preserve_default=False,
        ),
    ]
