# Generated by Django 3.2.9 on 2022-02-26 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_reviews_star'),
        ('shop', '0012_products_detail'),
    ]

    operations = [
    ]
