# Generated by Django 3.2.9 on 2022-02-28 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_merge_0006_alter_reviews_star_0012_products_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='ip',
            field=models.CharField(default=1, max_length=15, verbose_name='IP Адрес'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
