# Generated by Django 3.2.9 on 2022-02-28 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20220228_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='ip',
        ),
    ]
