# Generated by Django 3.2.9 on 2022-03-14 22:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0015_remove_reviews_ip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['-created'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AddField(
            model_name='products',
            name='favorites',
            field=models.ManyToManyField(related_name='favorites_users', to=settings.AUTH_USER_MODEL, verbose_name='Избранное'),
        ),
    ]
