# Generated by Django 3.2.9 on 2022-03-15 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_alter_products_options'),
        ('shop', '0016_auto_20220314_2223'),
    ]

    operations = [
    ]
