# Generated by Django 3.2.9 on 2022-03-19 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_merge_20220315_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='email',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='name',
        ),
    ]
