# Generated by Django 3.2.9 on 2022-03-19 08:19

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auto_20220319_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='star',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.fields.CharField, to='shop.ratingstar', verbose_name='Звезды'),
        ),
    ]
