# Generated by Django 3.2.9 on 2022-03-19 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0019_alter_reviews_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorites_users', to=settings.AUTH_USER_MODEL, verbose_name='Избранное'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='star',
            field=models.ForeignKey(null=True, on_delete=django.db.models.fields.CharField, to='shop.ratingstar', verbose_name='Звезды'),
        ),
    ]
